### ISSUE TITLE
Ajouter un annexe sur le RGPD ?

### ISSUE THREAD

**Issue by Guts** [isogeo/doc-isogeo-help#1]
L'idée serait d'avoir une page résumant les informations transmises dès février 2018 en détaillant les infos gérées par la plateforme et le lien de désinscription à la newsletter.

**Comment by vblanlot** [comment]
👍

**Comment by Guts** [comment]
@vblanlot http://help.qa.isogeo.com/admin/fr/appendices/gdpr.html

**Comment by vblanlot** [comment]
👍

**Comment by Guts** [comment]
Passé en prod depuis : https://prodisogeohelp.z28.web.core.windows.net/admin/fr/appendices/gdpr.html

A noter que la CUCM exprime un besoin d'introspection dans les données pour vérifier la conformité avec la législation. Plus clairement, ils veulent savoir dans quelle mesure les outils Isogeo permettraient de repérer les données concernées par le RGPD. C'est cependant HS avec la doc, donc je ferme.
