### ISSUE TITLE
Ajouter comment créer une métadonnée pour la cartothèque beta

### ISSUE THREAD

**Issue by Guts** [isogeo/doc-isogeo-help#3]
Résultat en QA : http://help.qa.isogeo.com/admin/fr/features/publish/share_maplibrary.html

**Comment by mathieubecker** [comment]
- supprimer "(beta)" du titre

- Ajouter "et enregistrer" après "3. Sélectionner l’application Cartothèque ;"

- Idem sur le point 4

- "6. enregistrer" -> ...en cliquant sur le bouton "Créer"

- Par exemple pour le thème “tourisme” vous devez saisir thematique:Tourisme >>> attention à la casse sur le mot "T.t.ourisme"
